services:
  - type: web
    name: email-onebox-backend
    runtime: node
    buildCommand: npm ci --include=dev
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
